### ISSUE TITLE
軟破機使用 1.6.2大氣層(1.5.0 all in one包) 無法進入hbl選單 會當機 

### ISSUE THREAD

**Issue by MaoMaoKing1** [tma533026/Atmosphere-1.0.0#1]
感謝辛苦整合
您好
...
請問 我是初代軟破機 有做虛擬系統
使用電腦TYPE-C線短接載入包內的hekate 6.0.7 payload.bin進入
將虛擬系統從16.1.0升級上 17.0.0後
將整ˋ張記憶卡刪除到只剩下emuMMCˋ這個資料夾
然後直接照慣例使用這包1.6.2正式版 整包copy進去
再次短接  成功進入虛擬系統後
當按住R+A想進入hbl內跑個DBI之類的
大氣層卻會跳錯誤訊息
Error Code: 2123-0011(0x167b)
Program: 0100000000000025
改用純淨版也一樣
請問要怎樣處理呢 謝謝@@
ps:
我有使用hekate中的工具
{ 歸檔位.rcm.觸摸 .pkg 1/2 }中的" {修復歸檔位}掃描過整張記憶卡
他顯示沒問題@@
.
補充說明 使用的記憶卡是Samsung Extreme 1TB
這個虛擬emuMMC含遊戲共約6xxGB
之前使用在16.1.0含以前版本毫無問題 @@

**Comment by tma533026** [comment]
請檢查根目錄下的hbmenu.nro是否存在，然後一定要使用Windows系統做複製更新。

**Comment by MaoMaoKing1** [comment]
晚安  我現在才下班
我所有執行的檔案包含hblmenu.nro直接是您這包解出來的
所以都是最新的
我也只有一台使用WINDOWS 10的電腦在格式化跟更新SWITCH的記憶卡.

唯一不同點是我的emuMMC空間有使用過Incongnito消除過序號
朋友傳給我看一篇之前有人在推特的發文(此文現已刪除)
所以我現在的狀況是只要開機成功 即使不進hbl
隨便在畫面上執行任何遊戲都會崩潰跳出上面說的訊息
亦既目前的大氣層17.0.0穩定版 依然無法避開800000000000012這個檔案存在的問題
.
看來目前最有可能的解方
就是我得想辦法進到這emuMMC的內部SYSTEM分區中
找到800000000000012分區 並刪除之
否則我這個有大量存檔的emuMMC就跟廢掉沒兩樣...
因為無法使用daybreak降板 QQ
[https://media.discordapp.net/attachments/450979137247510539/1163523437340393572/image.png](url)

**Comment by MaoMaoKing1** [comment]
再次回報 ，剛剛成功登入系統後　立刻將網路改成飛航模式只開藍芽＋NFC 關掉WIFI
機器就能正常使用了!
意思就是 針對序號被修改過的機器或emuMMC 
這台SWITCH的連網功能被徹底封印
無法使用LANPARTY 私人連網 或者用破解過的YOUTUBE看影片了 
意思是目前的17.0.0穩定版解決了 exosphere.ini 序號清空所造成的崩潰
但是若emuMMC本體的序號就是被清空的狀態 
那網路功能只能徹底封印!

**Comment by tma533026** [comment]
感謝您的問題回饋，不過建議不需要抹除序號這個步驟，我自己也是隱藏序號玩了正版跟虛擬系統兩邊有兩年多之久，並沒有什麼問題的！
而且虛擬系統wifi一直以來也都沒關閉過。
因此感謝您提供不經驗分享！

**Comment by MaoMaoKing1** [comment]
可以請教一下您是如何在不抹除序號的情況下隱藏序號的呢?
沒意外的話我應該是可以用Incongnito把之前備份的序號檔寫回去
只是寫回去後 就不知該如何隱藏序號正常用虛擬聯網而不影響了

**Comment by tma533026** [comment]
我整合包虛擬系統本身就預設隱藏了，除了真實系統為了能夠玩正版與朋友連線沒隱藏。

**Comment by MaoMaoKing1** [comment]
謝謝您的回答 
我使用的是這套Incongnito來物理隱藏的
https://www.cfwaifu.com/switch-incognito/
隱藏效果與您照片中一樣 是無序號的
所以您這包中的switch-incognito.nro所做出的隱藏 能在目前的wifi環境下不會崩潰囉?
我等等會將emu的物理序號還原後再次啟動並wifi聯網做測試
有後續在跟您回報 謝謝

**Comment by tma533026** [comment]
我整合包的隱藏序號是大氣層本身就有的功能開啟而已，不需要其他插件做輔助，並且使用原本作者給予含帶的功能比較穩定，畢竟不是額外寫的插件！

**Comment by MaoMaoKing1** [comment]
收到 以後就不幹這種物理刪除序號的事了
不過 其他跟我一樣物理刪除序號的人
若真實環境已誤升17.0.0 
emuMMC在刪除序號且無序號備份的情況下也升上17.0.0
則必須等逮這位作者更新支援17.0.0 才能有效將emuMMC回復序號
https://github.com/TTghostsemir/Incognito_RCM
只能等他更新了...

**Comment by tma533026** [comment]
會建議您目前可以使用插件的情況下，使用daybreak恢復能夠支援的版本再做還原試試看。

**Comment by MaoMaoKing1** [comment]
謝謝 我知道這作法 
但問題是我卡在真實系統已經升級上17 
所以是真實系統也降板回16來提取序號嗎?

**Comment by tma533026** [comment]
不，按理説虛擬系統不影響真實系統，雖然真實系統會影響虛擬系統，不過仍然可以試試看是否可以還原序號。
因此一直以來我都是推薦做雙系統的！
但這是有提前備份序號的作法！

**Comment by tma533026** [comment]
> 謝謝 我知道這作法 但問題是我卡在真實系統已經升級上17 所以是真實系統也降板回16來提取序號嗎?

您可以試試看bootloader/payloads/Picklock_RCM_17.0.0.bin
是否可以做到您要的功能！

**Comment by MaoMaoKing1** [comment]
是的 真實與虛擬互不影響 但問題是我之前是直接刪除虛擬的序號 沒有備份序號檔
所以必須回真實去提取序號備份
但是目前所有找到的Incognito RCM程序都無法讀取 17.0.0真實環境的序號做備份
然而
我不太敢在此時將真實系統降版
因為我不知道任天堂有沒有啥騷操作 
會在我降版後留下啥痕跡 導致我真實升級回17後 真實也出事
所以目前在Incognito作者沒更新的情況下 
最保險的方式就是開飛行模式到底等待作者更新 
.
至於我之前在虛擬環境開wifi  主要用途就是hbl的appstore線上商店以及emuamiibo的線上更新
還有免開機回真實看yt
等於是目前這幾個操作會暫時無法使用了
.
至於您包中的Picklock_RCM 它的用途是提取解碼用的keys.txt
用來打包跟解碼nsz nsp , xci xcz用的
他不能提取跟備份系統序號 Q_Q

**Comment by tma533026** [comment]
> 是的 真實與虛擬互不影響 但問題是我之前是直接刪除虛擬的序號 沒有備份序號檔 所以必須回真實去提取序號備份 但是目前所有找到的Incognito RCM程序都無法讀取 17.0.0真實環境的序號做備份 然而 我不太敢在此時將真實系統降版 因為我不知道任天堂有沒有啥騷操作 會在我降版後留下啥痕跡 導致我真實升級回17後 真實也出事 所以目前在Incognito作者沒更新的情況下 最保險的方式就是開飛行模式到底等待作者更新 . 至於我之前在虛擬環境開wifi 主要用途就是hbl的appstore線上商店以及emuamiibo的線上更新 還有免開機回真實看yt 等於是目前這幾個操作會暫時無法使用了 . 至於您包中的Picklock_RCM 它的用途是提取解碼用的keys.txt 用來打包跟解碼nsz nsp , xci xcz用的 他不能提取跟備份系統序號 Q_Q

好吧，因為我也沒有遇過跟特別刪除序號這件事，但原本是像到可以提取key來精簡系統應該序號會包含在裡面，或許可以利用他來還原序號！
看來是我想的太簡單了🥲

**Comment by MaoMaoKing1** [comment]
大氣層的隱藏序號功能應該是後來才添加的
早期大氣層並無此功能 
受害的用戶多數是我們這些從早年TX時代就開始玩虛擬的人
那個時候只有Incognito這個物理隱藏序號的手段! @@

**Comment by tma533026** [comment]
> 大氣層的隱藏序號功能應該是後來才添加的 早期大氣層並無此功能 受害的用戶多數是我們這些從早年TX時代就開始玩虛擬的人 那個時候只有Incognito這個物理隱藏序號的手段! @@

我不清楚您是在多早之前就開始使用，但我的整合包印象中0.19(大氣層版本)開始的，當下就有此功能的！

**Comment by MaoMaoKing1** [comment]
這樣說 TX SXOS用戶在TX沒被抓關門之前 
多數是根本不碰大氣層的 
所以在SXOS這些已付費的用戶手上 
使用Incognito來隱藏SXOX emu的虛擬序號是常見的手段
直到TX用戶沒得升級卡在9.2 必須認命才開始轉大氣層...
而大氣層此時也有提供TX的emu直接轉換成大氣層能用的辦法
我們這些老emuROM就沿用至今拉...

**Comment by MaoMaoKing1** [comment]
畢竟當年的SXOS可以做到整合更新後的XCI模擬卡匣直讀不須要安裝
所以SXOS當時的用戶不少
這點目前的大氣層環境 還沒看到其他作者敢開放

**Comment by tma533026** [comment]
> 這樣說 TX SXOS用戶在TX沒被抓關門之前 多數是根本不碰大氣層的 所以在SXOS這些已付費的用戶手上 使用Incognito來隱藏SXOX emu的虛擬序號是常見的手段 直到TX用戶沒得升級卡在9.2 必須認命才開始轉大氣層... 而大氣層此時也有提供TX的emu直接轉換成大氣層能用的辦法 我們這些老emuROM就沿用至今拉...

可以理解，我自身也是看TX不行了才動手自己研究後，才有這個整合包的。從軟改→自己動手硬改都這樣過來了，可能自己也屬於愛胡搞瞎搞研究3C的熱愛者，不可否認TX系統真的便利，但是現在大氣層也已經改善很多了！說真的改機為了超頻跟金手指的部份比較大。遊戲做得很棒還是買正版的！比如薩爾達

**Comment by tma533026** [comment]
> 畢竟當年的SXOS可以做到整合更新後的XCI模擬卡匣直讀不須要安裝 所以SXOS當時的用戶不少 這點目前的大氣層環境 還沒看到其他作者敢開放

這點我認為大氣層作者本身就不支持盜版，所以很多插件跟他無關！
我是很尊敬這位作者的，真的很盡心無私更新這個系統！

**Comment by MaoMaoKing1** [comment]
> > 這樣說 TX SXOS用戶在TX沒被抓關門之前 多數是根本不碰大氣層的 所以在SXOS這些已付費的用戶手上 使用Incognito來隱藏SXOX emu的虛擬序號是常見的手段 直到TX用戶沒得升級卡在9.2 必須認命才開始轉大氣層... 而大氣層此時也有提供TX的emu直接轉換成大氣層能用的辦法 我們這些老emuROM就沿用至今拉...
> 
> 可以理解，我自身也是看TX不行了才動手自己研究後，才有這個整合包的。從軟改→自己動手硬改都這樣過來了，可能自己也屬於愛胡搞瞎搞研究3C的熱愛者，不可否認TX系統真的便利，但是現在大氣層也已經改善很多了！手上碰過的SWITCH前前後後已經快十來台了，說真的改機為了超頻跟金手指的部份比較大。遊戲做得很棒還是買正版的！比如薩爾達

我自己正版環境包含下載版在內有5x個遊戲 
NSOP的會員也續了好幾年
只要做得好且真心喜歡 我都會買正版
當年為了搞定真實跟虛擬分離 
甚至因此讓四台switch被BAN過
(其中兩台是因為 玩寶可夢劍盾 真實跟虛擬兩台互連時 
忘了關閉虛擬這邊的金手指而影響到連正版環境的另一台一起被BAN)
.
至於大氣層正是因為他本身不支援盜版 
才會有那麼多額外插件如Incognito 及sighpatch 跟DBI等等必須由第三方作者開發的東西出現
不過 模擬卡匣這塊 倒是真的沒看到其他第三方作者敢出的XD

**Comment by tma533026** [comment]
> > > 這樣說 TX SXOS用戶在TX沒被抓關門之前 多數是根本不碰大氣層的 所以在SXOS這些已付費的用戶手上 使用Incognito來隱藏SXOX emu的虛擬序號是常見的手段 直到TX用戶沒得升級卡在9.2 必須認命才開始轉大氣層... 而大氣層此時也有提供TX的emu直接轉換成大氣層能用的辦法 我們這些老emuROM就沿用至今拉...
> > 
> > 
> > 可以理解，我自身也是看TX不行了才動手自己研究後，才有這個整合包的。從軟改→自己動手硬改都這樣過來了，可能自己也屬於愛胡搞瞎搞研究3C的熱愛者，不可否認TX系統真的便利，但是現在大氣層也已經改善很多了！手上碰過的SWITCH前前後後已經快十來台了，說真的改機為了超頻跟金手指的部份比較大。遊戲做得很棒還是買正版的！比如薩爾達
> 
> 我自己正版環境包含下載版在內有5x個遊戲 NSOP的會員也續了好幾年 只要做得好且真心喜歡 我都會買正版 當年為了搞定真實跟虛擬分離 甚至因此讓四台switch被BAN過 (其中兩台是因為 玩寶可夢劍盾 真實跟虛擬兩台互連時 忘了關閉虛擬這邊的金手指而影響到連正版環境的另一台一起被BAN) . 至於大氣層正是因為他本身不支援盜版 才會有那麼多額外插件如Incognito 及sighpatch 跟DBI等等必須由第三方作者開發的東西出現 不過 模擬卡匣這塊 倒是真的沒看到其他第三方作者敢出的XD

嗯，正確觀念。正版還是要支持的！
回到話題，希望您的序號早日修復！

**Comment by MaoMaoKing1** [comment]
問題回報
剛剛參照https://nh-server.github.io/switch-guide/extras/blocking_nintendo/ 的內容
追加上面連結文中所述emummc.txt
即可解決序號問題
原先的default.txt內只有擋掉一個任天堂server
====
# Nintendo telemetry servers
127.0.0.1 receive-%.dg.srv.nintendo.net receive-%.er.srv.nintendo.net
====
新的檔案多了這串
# 90DNS-equivalent
127.0.0.1 *nintendo.com
127.0.0.1 *nintendo.net
127.0.0.1 *nintendo.jp
127.0.0.1 *nintendo.co.jp
127.0.0.1 *nintendo.co.uk
127.0.0.1 *nintendo-europe.com
127.0.0.1 *nintendowifi.net
127.0.0.1 *nintendo.es
127.0.0.1 *nintendo.co.kr
127.0.0.1 *nintendo.tw
127.0.0.1 *nintendo.com.hk
127.0.0.1 *nintendo.com.au
127.0.0.1 *nintendo.co.nz
127.0.0.1 *nintendo.at
127.0.0.1 *nintendo.be
127.0.0.1 *nintendods.cz
127.0.0.1 *nintendo.dk
127.0.0.1 *nintendo.de
127.0.0.1 *nintendo.fi
127.0.0.1 *nintendo.fr
127.0.0.1 *nintendo.gr
127.0.0.1 *nintendo.hu
127.0.0.1 *nintendo.it
127.0.0.1 *nintendo.nl
127.0.0.1 *nintendo.no
127.0.0.1 *nintendo.pt
127.0.0.1 *nintendo.ru
127.0.0.1 *nintendo.co.za
127.0.0.1 *nintendo.se
127.0.0.1 *nintendo.ch
127.0.0.1 *nintendo.pl
127.0.0.1 *nintendoswitch.com
127.0.0.1 *nintendoswitch.com.cn
127.0.0.1 *nintendoswitch.cn
95.216.149.205 *conntest.nintendowifi.net
95.216.149.205 *ctest.cdn.nintendo.net

**Comment by MaoMaoKing1** [comment]
原先有找到這個可備份並回復17.0.0 prodinfo的方式
但不知為何 我使用後一樣是XA0000
改用上面的障蔽全部任天堂server搞定
https://www.reddit.com/r/SwitchPirates/comments/17pu77a/best_way_to_restore_prodinfo_on_incognito_switch/
